tests/intel/kms_pm_dc: Fix compilation on arm64
Fix compilation on arm64, where following error occurs:

../tests/intel/kms_pm_dc.c:428:16: error: implicit declaration of function ‘poll’; did you mean ‘powl’? [-Werror=implicit-function-declaration]
  428 |   igt_assert_f(poll(&pfd, 1, timeout_ms) > 0,
      |                ^~~~

While at this add a newline to separate system includes
from igt ones.

Fix also a compilation warning in other place:

../tests/intel/kms_pm_dc.c:322:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  322 |         color_t red_green_blue[] = {
      |         ^~~~~~~

Fixes: e4a428ca3a46 ("tests/intel/kms_pm_dc: Detect frame drops via page-flip events")
Cc: Jeevan B <jeevan.b@intel.com>
Cc: Dibin Moolakadan Subrahmanian <dibin.moolakadan.subrahmanian@intel.com>
Cc: "Zbigniew Kempczyński" <zbigniew.kempczynski@intel.com>
Signed-off-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>
Reviewed-by: Zbigniew Kempczyński <zbigniew.kempczynski@intel.com>